/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies.index'
import { Route as PoliciesIdRouteImport } from './routes/policies.$id'
import { Route as MastersTpaRouteImport } from './routes/masters.tpa'
import { Route as MastersPolicyTypesRouteImport } from './routes/masters.policy-types'
import { Route as MastersCustomersRouteImport } from './routes/masters.customers'
import { Route as MastersCompaniesRouteImport } from './routes/masters.companies'
import { Route as MastersBanksRouteImport } from './routes/masters.banks'
import { Route as MastersAgentsRouteImport } from './routes/masters.agents'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as AccountsCompanyBrokerageRouteImport } from './routes/accounts.company-brokerage'
import { Route as AccountsAgentBrokerageRouteImport } from './routes/accounts.agent-brokerage'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PoliciesRoute,
} as any)
const PoliciesIdRoute = PoliciesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PoliciesRoute,
} as any)
const MastersTpaRoute = MastersTpaRouteImport.update({
  id: '/masters/tpa',
  path: '/masters/tpa',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersPolicyTypesRoute = MastersPolicyTypesRouteImport.update({
  id: '/masters/policy-types',
  path: '/masters/policy-types',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCustomersRoute = MastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCompaniesRoute = MastersCompaniesRouteImport.update({
  id: '/masters/companies',
  path: '/masters/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersBanksRoute = MastersBanksRouteImport.update({
  id: '/masters/banks',
  path: '/masters/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersAgentsRoute = MastersAgentsRouteImport.update({
  id: '/masters/agents',
  path: '/masters/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const AccountsCompanyBrokerageRoute =
  AccountsCompanyBrokerageRouteImport.update({
    id: '/accounts/company-brokerage',
    path: '/accounts/company-brokerage',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsAgentBrokerageRoute = AccountsAgentBrokerageRouteImport.update({
  id: '/accounts/agent-brokerage',
  path: '/accounts/agent-brokerage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/claims': typeof ClaimsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/quotations': typeof QuotationsRoute
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/accounts/agent-brokerage': typeof AccountsAgentBrokerageRoute
  '/accounts/company-brokerage': typeof AccountsCompanyBrokerageRoute
  '/customers/$id': typeof CustomersIdRoute
  '/masters/agents': typeof MastersAgentsRoute
  '/masters/banks': typeof MastersBanksRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/policy-types': typeof MastersPolicyTypesRoute
  '/masters/tpa': typeof MastersTpaRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/': typeof PoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/claims': typeof ClaimsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/login': typeof LoginRoute
  '/quotations': typeof QuotationsRoute
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/accounts/agent-brokerage': typeof AccountsAgentBrokerageRoute
  '/accounts/company-brokerage': typeof AccountsCompanyBrokerageRoute
  '/customers/$id': typeof CustomersIdRoute
  '/masters/agents': typeof MastersAgentsRoute
  '/masters/banks': typeof MastersBanksRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/policy-types': typeof MastersPolicyTypesRoute
  '/masters/tpa': typeof MastersTpaRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies': typeof PoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/claims': typeof ClaimsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/login': typeof LoginRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/quotations': typeof QuotationsRoute
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRoute
  '/accounts/agent-brokerage': typeof AccountsAgentBrokerageRoute
  '/accounts/company-brokerage': typeof AccountsCompanyBrokerageRoute
  '/customers/$id': typeof CustomersIdRoute
  '/masters/agents': typeof MastersAgentsRoute
  '/masters/banks': typeof MastersBanksRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/policy-types': typeof MastersPolicyTypesRoute
  '/masters/tpa': typeof MastersTpaRoute
  '/policies/$id': typeof PoliciesIdRoute
  '/policies/': typeof PoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/claims'
    | '/customers'
    | '/login'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/accounts/agent-brokerage'
    | '/accounts/company-brokerage'
    | '/customers/$id'
    | '/masters/agents'
    | '/masters/banks'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/policy-types'
    | '/masters/tpa'
    | '/policies/$id'
    | '/policies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/claims'
    | '/customers'
    | '/login'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/accounts/agent-brokerage'
    | '/accounts/company-brokerage'
    | '/customers/$id'
    | '/masters/agents'
    | '/masters/banks'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/policy-types'
    | '/masters/tpa'
    | '/policies/$id'
    | '/policies'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/claims'
    | '/customers'
    | '/login'
    | '/policies'
    | '/quotations'
    | '/renewals'
    | '/reports'
    | '/accounts/agent-brokerage'
    | '/accounts/company-brokerage'
    | '/customers/$id'
    | '/masters/agents'
    | '/masters/banks'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/policy-types'
    | '/masters/tpa'
    | '/policies/$id'
    | '/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ClaimsRoute: typeof ClaimsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
  QuotationsRoute: typeof QuotationsRoute
  RenewalsRoute: typeof RenewalsRoute
  ReportsRoute: typeof ReportsRoute
  AccountsAgentBrokerageRoute: typeof AccountsAgentBrokerageRoute
  AccountsCompanyBrokerageRoute: typeof AccountsCompanyBrokerageRoute
  MastersAgentsRoute: typeof MastersAgentsRoute
  MastersBanksRoute: typeof MastersBanksRoute
  MastersCompaniesRoute: typeof MastersCompaniesRoute
  MastersCustomersRoute: typeof MastersCustomersRoute
  MastersPolicyTypesRoute: typeof MastersPolicyTypesRoute
  MastersTpaRoute: typeof MastersTpaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/policies/$id': {
      id: '/policies/$id'
      path: '/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof PoliciesIdRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/masters/tpa': {
      id: '/masters/tpa'
      path: '/masters/tpa'
      fullPath: '/masters/tpa'
      preLoaderRoute: typeof MastersTpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/policy-types': {
      id: '/masters/policy-types'
      path: '/masters/policy-types'
      fullPath: '/masters/policy-types'
      preLoaderRoute: typeof MastersPolicyTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/customers': {
      id: '/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof MastersCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/companies': {
      id: '/masters/companies'
      path: '/masters/companies'
      fullPath: '/masters/companies'
      preLoaderRoute: typeof MastersCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/banks': {
      id: '/masters/banks'
      path: '/masters/banks'
      fullPath: '/masters/banks'
      preLoaderRoute: typeof MastersBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/agents': {
      id: '/masters/agents'
      path: '/masters/agents'
      fullPath: '/masters/agents'
      preLoaderRoute: typeof MastersAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/accounts/company-brokerage': {
      id: '/accounts/company-brokerage'
      path: '/accounts/company-brokerage'
      fullPath: '/accounts/company-brokerage'
      preLoaderRoute: typeof AccountsCompanyBrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/agent-brokerage': {
      id: '/accounts/agent-brokerage'
      path: '/accounts/agent-brokerage'
      fullPath: '/accounts/agent-brokerage'
      preLoaderRoute: typeof AccountsAgentBrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface PoliciesRouteChildren {
  PoliciesIdRoute: typeof PoliciesIdRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesIdRoute: PoliciesIdRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ClaimsRoute: ClaimsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
  QuotationsRoute: QuotationsRoute,
  RenewalsRoute: RenewalsRoute,
  ReportsRoute: ReportsRoute,
  AccountsAgentBrokerageRoute: AccountsAgentBrokerageRoute,
  AccountsCompanyBrokerageRoute: AccountsCompanyBrokerageRoute,
  MastersAgentsRoute: MastersAgentsRoute,
  MastersBanksRoute: MastersBanksRoute,
  MastersCompaniesRoute: MastersCompaniesRoute,
  MastersCustomersRoute: MastersCustomersRoute,
  MastersPolicyTypesRoute: MastersPolicyTypesRoute,
  MastersTpaRoute: MastersTpaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
